// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgtolkmdzhmwotkvbone.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndG9sa21kemhtd290a3Zib25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTY0MzcsImV4cCI6MjA2MzQzMjQzN30.RAfebq7ysLsa8VBSDjcyCRRBU3fXinY7dD2sZ6Ejgw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);